language: node_js
node_js:
- '7'
notifications:
  slack:
    secure: Uk80qk39js5nWhANZftWUOHSB9ZX9Uv/9iK2WevbuNJ4j0KQUTlcb6mhzDVgKRx+GCFjIteCiIepsZ1HTXQX9WxLHVKGbiWuYHDr7WhJ4rBeC3lTCbglfYgWtaylz4pTtAy+AWYKc7GzEo1UCZMi+IotP8Sov+vrJrpCJzX6vNqUpAP/l5ROwA+v7GW+b+FjUBn0cdcvJWDHmtM2eaSxvXEqQlfZyr8qAiWYoDOzUzdlrBeC2YCKXdiH9cnLAUBiqj+H9AfyebERE2uB3tKBJZYzQNSuG4eevQ7p49h1SwD9BXEYD40z8L2xTsVFHIB5Lpg49PKLZcB5C7ZEuM2Nx4rU68MvZuep2+ZBKRv+r1OqcXKLosocSqKWpoN2aLzQC/tr/ERY94bzvnRxKtWmMsngMByskzrlWNKW62GYyzxnOdNtNncyy5bsp8B6zjhwYckSNgl/wWHlb11SFkX8KFbgZ//vYJTPH5d2lfyssocWQC+eV8NdwLmzO8+/IUtyw3g8vy6HoutleIjP5NR15tHK/SXHsr62C7zCrDwXfLup5rxiGdyjoo/to/EDmd/sfrWLPCmH+Ssdz4WbVB9XyG2FYKofduEYKDlxrCno4v4HWSkC/hfRkuTJFnpPAjMDLz5pCr3Nl4RpxCwKOa8xMGfkALmT3reKWWrm69R7kWk=
